### ISSUE TITLE
Missing box for newsletter email subscription

### ISSUE THREAD

**Issue by kernc** [biolab/orange-web#78]
Website is missing such a box.

**Comment by ajdapretnar** [comment]
E-mail subscription to what?

**Comment by kernc** [comment]
The [newsletter](https://biolab.us15.list-manage.com/subscribe?u=2cad1f1cbf3a532a77efe4354&id=6f257f15ff).

**Comment by ajdapretnar** [comment]
This is not a newsletter, it's an e-mail course. And there is a box appearing on the website if you hang in there for more than x time.

<img width="942" alt="screen shot 2017-04-26 at 12 39 41" src="https://cloud.githubusercontent.com/assets/12524972/25430574/7729f11e-2a7d-11e7-8749-d90cfc218146.png">
