### ISSUE TITLE
Errors raised by third party add-on

### ISSUE THREAD

**Issue by jerneju** [biolab/orange-web#86]
##### Expected behavior
Developers which are in charge of a third party add-on should be informed about an error which takes place in their code. Error report should be send to their Sentry account or wherever else.

##### Actual behavior
Error report is send only to Sentry Biolab account.

**Comment by ajdapretnar** [comment]
Has this been fixed? Or should I rather say - do we hardcode all external add-ons for Sentry or can we somehow accept only errors from supported add-ons?

**Comment by jerneju** [comment]
Yes, authors of one third party add-on now receive error reports. Other interested parties can still express interest and they are welcome to participate in our error reports sharing program.
